import json
import boto3
import logging
import uuid
from datetime import datetime, timezone

logger = logging.getLogger()
logger.setLevel(logging.INFO)

dynamodb = boto3.resource("dynamodb")
table = dynamodb.Table("BonTech-Security-Incidents")

sns = boto3.client("sns")
iam = boto3.client("iam")

SNS_TOPIC_ARN = "arn:aws:sns:us-east-1:<ACCOUNT-ID>:BonTech-Security-Alerts"

REMEDIATION_USER = "BonTech-Remediation-Test-User"
REMEDIATION_POLICY_ARN = "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"


def lambda_handler(event, context):
    logger.info("Received event: %s", json.dumps(event))

    if event.get("detail-type") == "AWS API Call via CloudTrail":
        detail = event.get("detail", {})
        event_name = detail.get("eventName", "UnknownIAMEvent")
        request_parameters = detail.get("requestParameters", {})
        user_name = request_parameters.get("userName")
        policy_arn = request_parameters.get("policyArn")

        incident = {
            "incident_id": f"INC-{uuid.uuid4().hex[:8].upper()}",
            "event_type": event_name,
            "severity": "HIGH",
            "status": "OPEN",
            "source": "EventBridge/CloudTrail",
            "description": f"Sensitive IAM activity detected: {event_name}",
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }

        # Controlled automated remediation for the dedicated lab test case.
        if (
            event_name == "AttachUserPolicy"
            and user_name == REMEDIATION_USER
            and policy_arn == REMEDIATION_POLICY_ARN
        ):
            iam.detach_user_policy(
                UserName=user_name,
                PolicyArn=policy_arn,
            )

            incident["status"] = "REMEDIATED"
            incident["description"] = (
                f"Unauthorized policy automatically detached from {user_name}: "
                f"{policy_arn}"
            )

            logger.info(
                "Automated remediation successful | User: %s | Policy: %s",
                user_name,
                policy_arn,
            )

    else:
        incident = {
            "incident_id": event["incident_id"],
            "event_type": event["event_type"],
            "severity": event["severity"],
            "status": event["status"],
            "source": event["source"],
            "description": event["description"],
        }

    logger.info(
        "Processing incident: %s | Event: %s | Severity: %s | Status: %s",
        incident["incident_id"],
        incident["event_type"],
        incident["severity"],
        incident["status"],
    )

    table.put_item(Item=incident)
    logger.info("Incident %s successfully stored in DynamoDB", incident["incident_id"])

    alert_message = f"""BONTECH CLOUD SECURITY ALERT

Incident ID: {incident['incident_id']}
Event Type: {incident['event_type']}
Severity: {incident['severity']}
Status: {incident['status']}
Source: {incident['source']}
Description: {incident['description']}

Automated alert generated by the BonTech Serverless Security Incident Automation system.
"""

    sns.publish(
        TopicArn=SNS_TOPIC_ARN,
        Subject=f"BonTech Security Alert - {incident['event_type']}",
        Message=alert_message,
    )

    logger.info("SNS alert successfully published for incident %s", incident["incident_id"])

    return {
        "statusCode": 200,
        "body": json.dumps("Incident successfully processed"),
    }
